server:
  port: 8080
spring:
  application:
    name: k8s-demo
  datasource:
    url: jdbc:mariadb://mariadb-service:3306/k8s_demo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
logging:
  level:
    root: info
    com.kevin.demo: debug
    org.hibernate.show_sql: debug
    org.hibernate.orm.jdbc.bind: trace
management:
  endpoints:
    web:
      exposure:
        include: health
